### ISSUE TITLE
make_tokenizer tokenisers return generators, Parser expects sequences

### ISSUE THREAD

**Issue by gsnedders** [vlasovskikh/funcparserlib#44]
```
from funcparserlib.lexer import make_tokenizer
from funcparserlib.parser import some

tokenize = make_tokenizer([
    (u'x', (ur'x',)),
])

some(lambda t: t.type == "x").parse(tokenize("x"))
```

results in

```
Traceback (most recent call last):
  File "/Users/gsnedders/Documents/other-projects/funcparserlib/funcparserlib/funcparserlib/tests/test_parsing.py", line 76, in test_tokenize
    some(lambda t: t.type == "x").parse(tokenize("x"))
  File "/Users/gsnedders/Documents/other-projects/funcparserlib/funcparserlib/funcparserlib/parser.py", line 121, in parse
    (tree, _) = self.run(tokens, State())
  File "/Users/gsnedders/Documents/other-projects/funcparserlib/funcparserlib/funcparserlib/parser.py", line 309, in _some
    if s.pos >= len(tokens):
TypeError: object of type 'generator' has no len()
```

`tokenize("x")` is a generator, and you can't call `len` on a generator.

**Comment by jtprobst** [comment]
I'm facing the same issue. Are there any updates?

**Comment by jtprobst** [comment]
I have temporarily worked around it by doing `parse(list(tokenize(s)))`
